[package]
name = "parse_hcdiff"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = { version = "0.46.0", features = ["lazy", "is_in", "strings", "regex", "rows", "dtype-array", "zip_with"] }
polars-rows-iter = "0.9.2"
rust-htslib = { version = "0.49.0", default-featurese = false }
